// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScofieldAsg10Cars.Models;

namespace ScofieldAsg10Cars.Migrations
{
    [DbContext(typeof(CarContext))]
    [Migration("20200425140118_v2")]
    partial class v2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ScofieldAsg10Cars.Models.Car", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MakeModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Color = "Silver",
                            MakeModel = "Plymouth Horizon Hatch",
                            Mileage = 65124,
                            Price = 300,
                            Year = 1983
                        },
                        new
                        {
                            ID = 2,
                            Color = "Burnt Orange",
                            MakeModel = "Chevrolet Chevette",
                            Mileage = 75894,
                            Price = 450,
                            Year = 1976
                        },
                        new
                        {
                            ID = 3,
                            Color = "Red/White",
                            MakeModel = "Ford F-150",
                            Mileage = 74358,
                            Price = 1200,
                            Year = 1987
                        },
                        new
                        {
                            ID = 4,
                            Color = "Forest Green",
                            MakeModel = "Saab 900S",
                            Mileage = 64124,
                            Price = 2100,
                            Year = 1994
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
